##
# Kubernetes deployment configuration for running SFTP alongside Nextcloud for
# one or more shares.
#
# @author Guy Elsmore-Paddock (guy@inveniem.com)
# @copyright Copyright (c) 2019, Inveniem
# @license GNU AGPL version 3 or any later version
#
apiVersion: apps/v1
kind: Deployment
metadata:
  name: sftp
spec:
  replicas: 1
  revisionHistoryLimit: 2
  selector:
    matchLabels:
      app: frontend-sftp
  template:
    metadata:
      labels:
        app: frontend-sftp
        role: frontend
    spec:
      containers:
        # Container: The SFTP server.
        - name: frontend-sftp
          image: "atmoz/sftp:alpine"
          ports:
            - containerPort: 22
          resources:
            requests:
              cpu: 100m
              memory: 64Mi
            limits:
              cpu: 500m
              memory: 128Mi
          volumeMounts:
            - name: volume-secret-ssh-host-keys
              mountPath: /etc/ssh/ssh_host_ed25519_key
              subPath: ssh_host_ed25519_key
              readOnly: true
            - name: volume-secret-ssh-host-keys
              mountPath: /etc/ssh/ssh_host_rsa_key
              subPath: ssh_host_rsa_key
              readOnly: true
            # HACK: Until AKS supports pod presets, we have to kludge the dynamic
            # mounts in via a variable expansion. Do not modify the last line of
            # this comment; it gets expanded and replaced automatically when this
            # file is pre-processed. Remove this entire comment when switching over
            # to using pod presets.
            #
            # ${FILE_SHARE_VOLUME_MOUNT_LINES}
          env:
            - name: SFTP_USERS
              value: "${SFTP_USER_STRING}"
      volumes:
        - name: volume-secret-ssh-host-keys
          secret:
            secretName: "${KUBE_SFTP_CREDS_SECRET}"
            defaultMode: 0400
        # HACK: Until AKS supports pod presets, we have to kludge the dynamic
        # mounts in via a variable expansion. Do not modify the last line of
        # this comment; it gets expanded and replaced automatically when this
        # file is pre-processed. Remove this entire comment when switching over
        # to using pod presets.
        #
        # ${FILE_SHARE_VOLUME_LINES}
---
apiVersion: v1
kind: Service
metadata:
  name: external-sftp
  labels:
    role: external-service
spec:
  type: LoadBalancer
  ports:
    - port: 22889
      targetPort: 22
  selector:
    app: frontend-sftp
