##
# Dockerfile for an Nginx reverse proxy and static content server for Nextcloud.
#
# This was borrowed from https://github.com/nextcloud/docker.
#
FROM nginx:1

COPY nginx.conf /etc/nginx/nginx.conf
