##
# Kustomization component for using Nginx with PHP-FPM to run Nextcloud.
#
# @author Guy Elsmore-Paddock (guy@inveniem.com)
# @copyright Copyright (c) 2022, Inveniem
# @license GNU AGPL version 3 or any later version
#
apiVersion: kustomize.config.k8s.io/v1alpha1
kind: Component

resources:
  - manifests/app-nextcloud.nginx-fpm.yaml
