##
# Kustomize plugin configuration for using SOPS to decrypt Nextcloud secrets.
#
# This gets invoked by Kustomize to decrypt secrets on the fly while generating
# the output manifests for the overlay.
#
# @author Guy Elsmore-Paddock (guy@inveniem.com)
# @copyright Copyright (c) 2019-2022, Inveniem
# @license GNU AGPL version 3 or any later version
#
apiVersion: viaduct.ai/v1
kind: ksops
metadata:
  name: sops-secret-generator-nextcloud
files:
  - manifests/secrets-mysql.enc.yaml
  - manifests/secrets-nextcloud.enc.yaml
  - manifests/secrets-redis.enc.yaml
  - manifests/generated/secrets-azure_files.enc.yaml
