##
# Kustomize plugin configuration for using SOPS to decrypt SFTP secrets.
#
# This gets invoked by Kustomize to decrypt secrets on the fly while generating
# the output manifests for the overlay.
#
# @author Guy Elsmore-Paddock (guy@inveniem.com)
# @copyright Copyright (c) 2019-2022, Inveniem
# @license GNU AGPL version 3 or any later version
#
apiVersion: viaduct.ai/v1
kind: ksops
metadata:
  name: sops-secret-generator-sftp
files:
  - manifests/generated/secrets-sftp-host-keys.enc.yaml
