#!/usr/bin/env bash

set -e
set -u

OUTFILE="./generated/setup_newrelic.sh"

SCRIPT_DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" >/dev/null 2>&1 && pwd )"

cd "${SCRIPT_DIR}"

source '../../config.env'

mkdir -p ./generated

echo "#!/usr/bin/env bash" > "${OUTFILE}"
echo '' >> "${OUTFILE}"

echo '# This file was generated by "generate_nr_setup_commands.sh". DO NOT EDIT.' >> "${OUTFILE}"
echo '' >> "${OUTFILE}"

echo "set -e" >> "${OUTFILE}"
echo "set -u" >> "${OUTFILE}"
echo '' >> "${OUTFILE}"

if [[ "${NEW_RELIC_AGENT_URL:-}" != "" && \
      "${NEW_RELIC_KEY:-}" != "" && \
      "${NEW_RELIC_APP:-}" != "" ]]; then
    echo "\
curl -L '${NEW_RELIC_AGENT_URL}' | \
    tar -C /tmp -zx && \
        export NR_INSTALL_USE_CP_NOT_LN=1 && \
        export NR_INSTALL_SILENT=1 && \
        /tmp/newrelic-php5-*/newrelic-install install && \
        rm -rf /tmp/newrelic-php5-* /tmp/nrinstall* && \
        sed -i -e 's/\"REPLACE_WITH_REAL_KEY\"/\"${NEW_RELIC_KEY}\"/' \
            -e 's/newrelic.appname = \"PHP Application\"/newrelic.appname = \"${NEW_RELIC_APP}\"/' \
            /usr/local/etc/php/conf.d/newrelic.ini" >> "${OUTFILE}"
else
    echo "# New Relic Monitoring disabled in config.env" >> "${OUTFILE}"
fi
