##
# Redis database connection secrets.
#
# This is an EXAMPLE file. Customize for your environment and then encrypt it
# with ./rigger encrypt-secrets! If you have multiple environments, you can
# create multiple copies of the containing, sample overlay folder and customize
# manifests in each one to match your environments.
#
# @author Guy Elsmore-Paddock (guy@inveniem.com)
# @copyright Copyright (c) 2022, Inveniem
# @license GNU AGPL version 3 or any later version
#
apiVersion: v1
kind: Secret
metadata:
  name: "nextcloud-redis-creds"
type: Opaque
stringData:
  password: "MyRedisPassword"
---
apiVersion: v1
kind: Secret
metadata:
  name: "nextcloud-redis-config"
stringData:
  redis.conf: |
    maxmemory 496mb
    maxmemory-policy allkeys-lru

    requirepass "MyRedisPassword"
